AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SaveQuestionSolveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      FunctionName: save-question-solve
      CodeUri: src/
      Description: "Save question solves"
      MemorySize: 256
      Timeout: 30
      Tags:
        Stage: dev
        ServiceType: backend  
        crudType: Create      
        ResourceType: Lambda